spring:
  datasource:
    url: jdbc:h2:mem:person_test;DB_CLOSE_DELAY=-1
    username: sa
    password:
  redis:
    redisson:
      config: |
        singleServerConfig:
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          address: "${REDIS_URL:redis://127.0.0.1}:6379"
        threads: 16
        nettyThreads: 32
        transportMode: "NIO"

app:
  lock:
    waitTimeSeconds: 1
    leaseTimeSeconds: 5